# TravisCI
#
# @url: https://github.com/caskroom/homebrew-cask/blob/master/.travis.yml
# @url: https://docs.travis-ci.com/user/languages/objective-c/
# @url: https://docs.travis-ci.com/user/multi-os/
# @url: https://docs.travis-ci.com/user/reference/windows/
# @url: https://docs.brew.sh/Installation
# @url: https://docs.brew.sh/Homebrew-on-Linux
#
language: ruby

matrix:
  include:
    - os: osx
      osx_image: xcode12
    - os: linux
      dist: trusty
  fast_finish: true

before_install:
  - |
    if [[ $TRAVIS_OS_NAME != 'osx' ]]; then
      /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
      test -d ~/.linuxbrew && eval $(~/.linuxbrew/bin/brew shellenv)
      test -d /home/linuxbrew/.linuxbrew && eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)
      test -r ~/.bash_profile && echo "eval \$($(brew --prefix)/bin/brew shellenv)" >>~/.bash_profile
      echo "eval \$($(brew --prefix)/bin/brew shellenv)" >>~/.profile

      #ErrorFix: Install Perl
      # @see https://travis-ci.org/github/KazuakiM/homebrew-universal-ctags/jobs/683777821
      brew install perl -s
    fi

install:
  - brew install --HEAD --debug --verbose ./universal-ctags.rb

script:
  - ctags --version
  - brew test universal-ctags

notifications:
  email: false

# vim:fdl=0:sts=2:sw=2:ts=2
